package com.bhashai.app.ui.screens

import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.bhashai.app.data.model.WorksheetQuestionDto
import com.bhashai.app.data.repository.BhashAIRepository
import com.bhashai.app.ui.theme.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun WorksheetGeneratorScreen(
    repository: BhashAIRepository,
    onBack: () -> Unit
) {
    val context = LocalContext.current
    var isGenerated by remember { mutableStateOf(false) }
    var status by remember { mutableStateOf("DRAFT") }
    var questions by remember {
        mutableStateOf(
            listOf(
                WorksheetQuestionDto(
                    id = 1,
                    questionType = "Picture identification",
                    hindiPrompt = "🥭 चित्र देखकर फल का नाम लिखिए: यह _________ है।",
                    santaliPrompt = "🥭 ᱪᱤᱛᱟᱹᱨ ᱧᱮᱞ ᱠᱟᱛᱮ ᱡᱚ ᱨᱮᱭᱟᱜ ᱧᱩᱛᱩᱢ ᱚᱞ ᱢᱮ: ᱱᱚᱣᱟ ᱫᱚ _________ ᱠᱟᱱᱟ ᱾",
                    optionsHindi = null,
                    optionsSantali = null,
                    answerHindi = "आम",
                    answerSantali = "ᱩᱞ",
                    sourceReference = "Fruits.pdf (Page 1)",
                    audioUrl = null
                ),
                WorksheetQuestionDto(
                    id = 2,
                    questionType = "Multiple choice",
                    hindiPrompt = "इस फल का सही नाम क्या है? 🍎",
                    santaliPrompt = "ᱱᱚᱣᱟ ᱡᱚ ᱨᱮᱭᱟᱜ ᱥᱟᱹᱨᱤ ᱧᱩᱛᱩᱢ ᱪᱮᱫ? 🍎",
                    optionsHindi = listOf("सेब", "केला", "अंगूर"),
                    optionsSantali = listOf("ᱥᱮᱣ", "ᱠᱟᱭᱨᱟ", "ᱟᱝᱜᱩᱨ"),
                    answerHindi = "सेब",
                    answerSantali = "ᱥᱮᱣ",
                    sourceReference = "Fruits.pdf (Page 1)",
                    audioUrl = null
                )
            )
        )
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Worksheet Generator", fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = SurfaceWhite)
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .background(BackgroundLight)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Configuration Card
            Card(
                shape = RoundedCornerShape(12.dp),
                colors = CardDefaults.cardColors(containerColor = SurfaceWhite),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    Text("FLN WORKSHEET CONFIGURATION", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = TextMuted)

                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("Grade: Grade 1", fontWeight = FontWeight.SemiBold)
                        Text("Subject: Foundational Literacy", fontWeight = FontWeight.SemiBold)
                    }
                    Text("Language Pair: Hindi ➔ Santali (Ol Chiki)", color = PrimaryBlue, fontWeight = FontWeight.Bold)

                    Button(
                        onClick = {
                            isGenerated = true
                            Toast.makeText(context, "Worksheet generated from Class 1 Fruits lesson!", Toast.LENGTH_SHORT).show()
                        },
                        modifier = Modifier.fillMaxWidth(),
                        colors = ButtonDefaults.buttonColors(containerColor = PrimaryBlue)
                    ) {
                        Text("📄 GENERATE WORKSHEET", fontWeight = FontWeight.Bold)
                    }
                }
            }

            if (isGenerated) {
                // Status and Action Bar
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .background(SurfaceWhite, RoundedCornerShape(8.dp))
                        .padding(12.dp),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text("Status: $status", fontWeight = FontWeight.Bold, color = if (status == "APPROVED") SuccessGreen else WarningAmber)
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Button(
                            onClick = {
                                status = "APPROVED"
                                Toast.makeText(context, "Worksheet APPROVED by Teacher!", Toast.LENGTH_SHORT).show()
                            },
                            colors = ButtonDefaults.buttonColors(containerColor = SuccessGreen)
                        ) {
                            Text("Approve")
                        }
                        OutlinedButton(
                            onClick = {
                                Toast.makeText(context, "Exporting Printable A4 PDF...", Toast.LENGTH_SHORT).show()
                            }
                        ) {
                            Text("Export PDF")
                        }
                    }
                }

                // Questions Preview
                Text("Questions Preview (Teacher Review Mode):", fontWeight = FontWeight.Bold, fontSize = 14.sp)

                questions.forEach { q ->
                    Card(
                        shape = RoundedCornerShape(8.dp),
                        colors = CardDefaults.cardColors(containerColor = SurfaceWhite),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
                            Text("Q${q.id}. [${q.questionType}] - Source: ${q.sourceReference}", fontSize = 11.sp, color = TextMuted)
                            Text(q.hindiPrompt, fontWeight = FontWeight.SemiBold, fontSize = 14.sp)
                            Text(q.santaliPrompt, fontWeight = FontWeight.Bold, fontSize = 15.sp, color = AccentTeal)
                            Text("Answer: ${q.answerHindi} / ${q.answerSantali}", fontSize = 13.sp, color = PrimaryDark)
                        }
                    }
                }
            }
        }
    }
}
